sonar.projectKey=pickles-direct-mobile
sonar.projectName=Pickles Direct Mobile
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.language=dart

sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  **/*.config.dart,\
  lib/firebase_options.dart,\
  lib/core/storage/database/app_database.g.dart

sonar.coverage.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  lib/firebase_options.dart
