import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pickles_direct/core/constants/app_constants.dart';

// ignore: always_use_package_imports, document_ignores
// Part files generated by Drift must use a relative import — package-style
// imports are not supported for `part` directives in Dart.
part 'app_database.g.dart';

// ── Tables ────────────────────────────────────────────────────────────────────

/// Stores vendor asset submission drafts (all data encrypted at rest).
class SubmissionDrafts extends Table {
  TextColumn get id => text()();
  TextColumn get vendorId => text()();

  /// SubmissionStatus enum value stored as string.
  TextColumn get status => text()();

  /// JSON-encoded asset payload (encrypted).
  TextColumn get assetPayloadEncrypted => text()();

  /// Asset category key, e.g. "vehicles" | "industrial".
  TextColumn get assetCategory => text()();

  /// Human-readable asset label for list display.
  TextColumn get assetLabel => text()();

  RealColumn get gpsLat => real().nullable()();
  RealColumn get gpsLng => real().nullable()();

  IntColumn get photoCount => integer().withDefault(const Constant(0))();
  IntColumn get retryCount => integer().withDefault(const Constant(0))();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();
  DateTimeColumn get syncedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// References to locally stored photo files for a draft submission.
class SubmissionPhotos extends Table {
  TextColumn get id => text()();
  TextColumn get submissionId =>
      text().references(SubmissionDrafts, #id, onDelete: KeyAction.cascade)();

  /// Photo category key, e.g. "overview_front" | "serial_plate".
  TextColumn get categoryKey => text()();

  /// Absolute path to the compressed JPEG on device storage.
  TextColumn get localPath => text()();

  /// Original filename before compression.
  TextColumn get originalFilename => text()();

  IntColumn get fileSizeBytes => integer()();
  IntColumn get widthPx => integer()();
  IntColumn get heightPx => integer()();

  RealColumn get gpsLat => real().nullable()();
  RealColumn get gpsLng => real().nullable()();

  IntColumn get sortOrder => integer().withDefault(const Constant(0))();
  DateTimeColumn get capturedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Tracks sync queue entries — one row per asset in the sync pipeline.
class SyncQueue extends Table {
  TextColumn get id => text()();
  TextColumn get submissionId =>
      text().references(SubmissionDrafts, #id, onDelete: KeyAction.cascade)();

  /// SyncStatus enum value: pending | in_progress | failed | succeeded.
  TextColumn get syncStatus => text()();

  IntColumn get retryCount => integer().withDefault(const Constant(0))();
  TextColumn get lastErrorMessage => text().nullable()();

  DateTimeColumn get enqueuedAt => dateTime()();
  DateTimeColumn get nextRetryAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Stores server-submitted asset summaries (read-only, from CRM).
class SubmittedAssets extends Table {
  TextColumn get id => text()();
  TextColumn get vendorId => text()();
  TextColumn get remoteId => text()();

  /// Submission status from CRM, e.g. "valuation_pending" | "accepted".
  TextColumn get status => text()();

  TextColumn get assetLabel => text()();
  TextColumn get assetCategory => text()();

  /// JSON-encoded valuation response (nullable until valued).
  TextColumn get valuationPayload => text().nullable()();

  DateTimeColumn get submittedAt => dateTime()();
  DateTimeColumn get lastUpdatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Caches the asset schema configuration downloaded from middleware.
class AssetSchemas extends Table {
  TextColumn get categoryKey => text()();
  TextColumn get schemaJson => text()();
  TextColumn get version => text()();
  DateTimeColumn get cachedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {categoryKey};
}

// ── Database ──────────────────────────────────────────────────────────────────

@DriftDatabase(
  tables: [
    SubmissionDrafts,
    SubmissionPhotos,
    SyncQueue,
    SubmittedAssets,
    AssetSchemas,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => AppConstants.databaseVersion;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          // Future migrations added here per version bump.
        },
      );
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, AppConstants.databaseName));
    return NativeDatabase.createInBackground(file);
  });
}
