// Generated by FlutterFire CLI.
// Run: flutterfire configure --project=pickles-direct
//
// ⚠️  API keys and app IDs below must be filled in by Pickles Platform Ops
//     after running `flutterfire configure --project=pickles-direct`.
//     Store the generated file securely — do NOT commit real API keys to git.
//     The values marked REPLACE_ME are placeholders only.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      _ => web,
    };
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'pickles-direct',
    storageBucket: 'pickles-direct.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'pickles-direct',
    storageBucket: 'pickles-direct.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'pickles-direct',
    storageBucket: 'pickles-direct.firebasestorage.app',
    iosClientId: 'REPLACE_ME',
    iosBundleId: 'com.pickles.picklesdirect',
  );
}
